[package]
name = "bullsjit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aligned-vec = "0.6.1"
clap = { version = "4.5.20", features = ["derive"] }
libc = "0.2.161"
